SmartVMA/SmartVMA.Web/Areas/Dealer/Controllers/InspectionController.cs
using System;
using SmartVMA.Core.Services;
using SmartVMA.Infrastructure.Ioc;
using SmartVMA.Web.Controllers;
using System.Web.Mvc;
using SmartVMA.Infrastructure.AppContext;
using SmartVMA.Core.InputModels.ViewModels;
using SmartVMA.Core.Contracts;
using SmartVMA.Core.Enums;
using SmartVMA.Infrastructure.FileManager;
using SmartVMA.Resources;
using Rotativa;


namespace SmartVMA.Web.Areas.Dealer.Controllers
{
    [IocBindable(RegisterAsSelf = true)]
    public class InspectionController : BaseController
    {
        private readonly IInspectionService _service;
        private readonly IDealerCustomerService _dealerCustomerService;


        public InspectionController(IAppContext appContext, IInspectionService service, IDealerCustomerService dealerCustomerService) : base(appContext)
        {
            _service = service;
            _dealerCustomerService = dealerCustomerService;
        }

        [HttpGet]
        public ActionResult Index(int carId, long? inspectionId = null, long? appointmentPresentationId = null, int? customerId = null, int? mileage = null, int? transmission = null, int? driveline = null, int? enteredMileage = null, int? dealerVehicleId = null, string vin = null, int carIdUndetermined = 1)
        {
            InspectionViewModel model = _service.GetViewModel(inspectionId, appointmentPresentationId, transmission, driveline, enteredMileage);
            var customerInfo = _dealerCustomerService.GetCustomerInfo(customerId, carId, transmission, driveline, dealerVehicleId);
            if (customerInfo != null)
            {
                customerInfo.Mileage = enteredMileage;
                if (!string.IsNullOrEmpty(vin))
                {
                    customerInfo.VIN = vin;
                }
            }
            model.CustomerInfo = customerInfo ?? new CustomerInfoViewModel();
            model.CarIdUndetermined = carIdUndetermined;
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(InspectionViewModel model, string action, int carId, long? inspectionId = null, int? appointmentPresentationId = null, int? customerId = null, int? mileage = null, string transmission = null, string driveline = null, int? enteredMileage = null, int? dealerVehicleId = null, string vin = null, int carIdUndetermined = 1)
        {
            if (ModelState.IsValid)
            {
                var response = _service.AddSetInspection(model);
                if (response.IsSuccess)
                {
                    switch ((InspectionNavigationActions)Enum.Parse(typeof(InspectionNavigationActions), action, true))
                    {
                        case InspectionNavigationActions.LOF:
                            return RedirectToAction("Index", "LOF", new { carId, inspectionId, appointmentPresentationId, customerId, mileage, transmission, driveline, enteredMileage, dealerVehicleId, vin, carIdUndetermined });
                        case InspectionNavigationActions.Services:
                            return RedirectToAction("Index", "MenuPresentation", new { carId, inspectionId, appointmentPresentationId, customerId, mileage, transmission, driveline, enteredMileage, dealerVehicleId, vin, carIdUndetermined });
                    }
                }
                MapErrors(response.Errors);
            }
            return View(model);
        }

        [HttpPost]
        public void ResetInspection(long inspectionId)
        {
            _service.ResetInspection(inspectionId);
        }
        public ActionResult GetPhoto(int id)
        {
            var model = _service.GetPhoto(id);
            return View(model);
        }

        public ActionResult GetVehiclePhotos(long inspectionId)
        {
            return PartialView("_VehiclePhotos", _service.GetAllPhotos(inspectionId));
        }

        public ActionResult SavePhoto(string fileName, long inspectionId)
        {
            VehiclePhotoViewModel photo = new VehiclePhotoViewModel
            {
                FileName = fileName,
                InspectionId = inspectionId
            };
            var response = _service.AddPhoto(photo);
            MapErrors(response.Errors);
            return PartialView("_VehiclePhotos", _service.GetAllPhotos(inspectionId));
        }


        [HttpPost]
        public JsonResult AddDamageIndication(DamageIndicationViewModel model)
        {
            if (model != null)
            {
                var response = _service.SaveDamageIndication(model);
                return Json(response);
            }
            return Json(new { IsSuccess = "false" });
        }

        [HttpPost]
        public JsonResult DeleteDamageIndication(long id)
        {
            ServiceResponse response = new ServiceResponse();
            if (ModelState.IsValid)
            {
                response = _service.DeleteDamageIndication(id);
                return Json(response);
            }
            return Json(response);
        }

        [HttpPost]
        public ActionResult EditDamageIndication(DamageIndicationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = _service.SaveDamageIndication(model);
                return Json(response);
            }
            return View(model);
        }

        public ActionResult EditDamageIndication(long id)
        {
            var model = _service.GetDamageIndication(id);
            return View(model);
        }


        public ActionResult DeletePhoto(VehiclePhotoViewModel model)
        {
            ServiceResponse response = new ServiceResponse();
            if (ModelState.IsValid)
            {
                response = _service.DeletePhoto(model);
            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public string ViewVehicleInspectionPrintPdfFile(long? inspectionId, long? appointmentPresentationID, int dealerId, 
            string enteredMileage, string model, string make, string year,
            bool lFRimScratch, bool lRRimScratch, bool rFRimScratch, bool rRRimScratch, int? lFTireTypeId, int? lRTireTypeId, int? rFTireTypeId, int? rRTireTypeId)
        {
            if(inspectionId.HasValue && inspectionId.Value == -1)
            {
                inspectionId = null;
            }
            if (appointmentPresentationID.HasValue && appointmentPresentationID.Value == -1)
            {
                appointmentPresentationID = null;
            }

            var companySettings = IocManager.Resolve<ICompanyService>();
            var appPresentation = IocManager.Resolve<IAppointmentPresentationService>();
            var pdfDocumentService = IocManager.Resolve<IPdfDocumentService>();
            var fileManager = IocManager.Resolve<IFileManager>();
            string measurementUnit = companySettings.GetSettingAsInteger(CompanySettingsNames.MeasurementUnit) == (int)MeasurementUnits.Imperial ? Labels.Miles : Labels.km;
            
            PdfHeaderViewModel header = new PdfHeaderViewModel();

            header.CustomerInfo = pdfDocumentService.GetPdfHeaderCustomerInfoViewModel(dealerId, appointmentPresentationID.HasValue ? appointmentPresentationID.Value : -1);
            if (header.CustomerInfo == null)
            {
                header.CustomerInfo = new PdfHeaderCustomerInfoViewModel();
                header.CustomerInfo.VehicleMake = make;
                header.CustomerInfo.VehicleModel = model;
                header.CustomerInfo.VehicleYear = year;
            }

            header.CustomerInfo.DateString = header.CustomerInfo.Date == DateTime.MinValue ? DateTime.Now.ToString(companySettings.GetDateTimeFormat(CompanySettingsNames.DateFormat)) : header.CustomerInfo.Date.ToString(companySettings.GetDateTimeFormat(CompanySettingsNames.DateFormat));


            header.CustomerInfo.OdometerReading = string.Format("{0} {1}", enteredMileage, measurementUnit);

            var printAdvisorInformation = companySettings.GetSettingAsBool(CompanySettingsNames.PrintAdvisorInformation);
            if (printAdvisorInformation && AppContext.CurrentIdentity.UserId.HasValue)
            {
                header.ShowAdvisor = true;
                header.Advisor = pdfDocumentService.GetPdfHeaderAdvisorViewModel(AppContext.CurrentIdentity.UserId.Value);
            }

            header.ShowDealer = true;
            header.Dealer = pdfDocumentService.GetPdfHeaderDealerViewModel();
            header.Dealer.LogoImg = companySettings.GetCompanyLogoPath(CompanySettingsNames.CompanyLogo);
            var stream = fileManager.Read(header.Dealer.LogoImg);
            header.Dealer.LogoImgByteArray = fileManager.ReadStreamToByte(stream);
            
            var footer = pdfDocumentService.GetPdfFooterViewModel(appointmentPresentationID.HasValue ? appointmentPresentationID.Value : -1, header.CustomerInfo.Date == DateTime.MinValue ? DateTime.Now : header.CustomerInfo.Date);

            var modelWA = pdfDocumentService.GetWalkaroundInspectionPdfViewModel(inspectionId, appointmentPresentationID);

            modelWA.WalkaroundInspection.LFRimScratch = lFRimScratch;
            modelWA.WalkaroundInspection.LRRimScratch = lRRimScratch;
            modelWA.WalkaroundInspection.RFRimScratch = rFRimScratch;
            modelWA.WalkaroundInspection.RRRimScratch = rRRimScratch;            

            modelWA.WalkaroundInspection.LFTireTypeId = lFTireTypeId == -1 ? null : lFTireTypeId;
            modelWA.WalkaroundInspection.LRTireTypeId = lRTireTypeId == -1 ? null : lRTireTypeId;
            modelWA.WalkaroundInspection.RFTireTypeId = rFTireTypeId == -1 ? null : rFTireTypeId;
            modelWA.WalkaroundInspection.RRTireTypeId = rRTireTypeId == -1 ? null : rRTireTypeId;

            modelWA.Header = header;

            modelWA.Footer = footer;
            
            var pdf = new ViewAsPdf("PdfWalkaroundInspection", modelWA);

SmartVMA/SmartVMA.Web/Areas/Dealer/Views/Inspection/EditDamageIndication.cshtml
@model DamageIndicationViewModel
@{
    Layout = LayoutPaths.Modal;
    var hasComment = ViewBag.HasComment;
}

<div class="modal-form">
    <div class="modal-form-row filter-dropdown">
        @using (Html.BeginForm("", "Inspection", FormMethod.Post))
        {
            hasComment = (@Model.TypeId == 4);
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.InspectionId)
            @Html.HiddenFor(m => m.OffsetLeft)
            @Html.HiddenFor(m => m.OffsetTop)
            @Html.HiddenFor(m => m.ViewPointId)
            @Html.HiddenFor(m => m.TypeId)
            if (hasComment)
            {
                <div class="input-container row">
                    @Html.EditorFor(m => m.Comment, EditorTemplateNames.TextArea)
                </div>
            }
            else
            {
                <p>[Are you sure you want to delete this damage indication?]</p>
            }
        }
    </div>
</div>
@section buttons{
    <button type="button" class="btn btn-default" data-dismiss="modal">@Labels.Close</button>
    @if(hasComment){
        <button type="button" class="btn btn-primary btn-modal-submit" name="damage" data-action="EditDamageIndication">@Labels.Save</button>
    }
    <button type="button" class="btn btn-danger btn-delete" name="damage" data-action="DeleteDamageIndication" onclick="smartvma.inspection.deleteDamageIndication(@Model.Id)">@Labels.Delete</button>
}

SmartVMA/SmartVMA.Web/Areas/Dealer/Views/Inspection/GetPhoto.cshtml
@model VehiclePhotoViewModel
@{
    Layout = LayoutPaths.LargeModal;
}
<div class="inspection-img-container">
    <img src="@Model.Url" alt="Vehicle Photo" />
</div>
@Html.HiddenFor(m => m.Id)
@Html.HiddenFor(m => m.InspectionId)
@Html.HiddenFor(m => m.FileName)

@section buttons{
    <button type="button" class="btn btn-default" data-dismiss="modal">@Labels.Close</button>
    <button type="button" class="btn btn-info btn-modal-submit" onclick="smartvma.inspection.printPhoto('@Model.Url')">@Labels.Print</button>
    <button type="button" class="btn btn-danger btn-delete" name="photo" data-action="DeletePhoto" onclick="smartvma.inspection.deletePhoto(@Model.Id,@Model.InspectionId)">@Labels.Delete</button>
}

SmartVMA/SmartVMA.Web/Areas/Dealer/Views/Inspection/Index.cshtml
@using System.Web.Optimization
@model InspectionViewModel
@{
    ViewBag.Title = Labels.VehicleInspection;
    Layout = LayoutPaths.Default;
}

@using (Html.BeginForm("Index", "Inspection", new {customerId = Model.CustomerInfo?.Id, carId = Request["carId"], mileage = Request["mileage"], appointmentPresentationId = Request["appointmentPresentationId"], inspectionId = Model.Id, transmission = Request["transmission"], driveLine = Request["driveLine"], enteredMileage = Request["enteredMileage"], dealerVehicleId = Request["dealerVehicleId"], vin = Request["vin"], carIdUndetermined = Request["CarIdUndetermined"] }, FormMethod.Post))
{

    //Html.RenderPartial("_CustomerInfo", Model.CustomerInfo);

    <section class="inspection-customer customer-data">
        <h2>@Labels.VehicleInspection</h2>
        @*<span class="invoce-number">Invoice #: 1234567</span>*@
        @Html.Partial("_CustomerInfo", Model.CustomerInfo)
    </section>
    <section class="inspection-gallery">
        @Html.Partial("_ViewPoints", Model.ViewPoints)
    </section>
    <section class="inspection-properties">
        <div class="row">
            <div class="col-sm-4 ">
                <div class="damage-indication-holder">
                    @{Html.RenderPartial("_DamageIndicationTypes", Model.DamageIndicationTypes);}
                    <div class="damage-photo">
                        <div id="vehiclePhotos">
                            @{Html.RenderPartial("_VehiclePhotos", Model.VehiclePhotos);}
                        </div>
                        @Html.EditorFor(m => m.VehicleImageName, EditorTemplateNames.UploaderVehiclePhotos)
                        @*<div class="upload-img">
                                <input type="file" />
                            </div>*@
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="tire-wear modal-form">
                    <h4>@Labels.TireWearInspection</h4>
                    @Html.HiddenFor(m => Model.DamageIndicationJson)
                    @Html.HiddenFor(m => Model.Id)
                    @Html.HiddenFor(m => Model.AppointmentPresentationId)
                    @Html.HiddenFor(m => Model.EnteredMileage)
                    @Html.HiddenFor(m => Model.CustomerInfo.Year)
                    @Html.HiddenFor(m => Model.CustomerInfo.Make)
                    @Html.HiddenFor(m => Model.CustomerInfo.Model)
                    @Html.HiddenFor(m => Model.AppointmentPresentationStatus)

                    <input type="hidden" value='' id="damageIndications">

                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-5 col-sm-6 col-md-6 ">
                                <h4>@Labels.LeftFront</h4>
                                @Html.EditorFor(m => Model.LFRimScratch)
                                @{var i = 0;}
                                @foreach (var tireType in Model.TireTypes)
                                {
                                    @Html.EditorFor(model => model.LFTireTypeId, EditorTemplateNames.RadioInputGroup, new
                               {
                                   RadioGroupName = "LFTireTypeId",
                                   RadioButtonValue = (i++),
                                   CurrentRadioButtonValue = Model.LFTireTypeId,
                                   Label = tireType
                               })
                                }
                            </div>

                            <div class="col-lg-5 col-sm-6 col-md-6 ">
                                <h4>@Labels.LeftRear</h4>
                                @Html.EditorFor(m => Model.LRRimScratch)
                                @{i = 0;}
                                @foreach (var tireType in Model.TireTypes)
                                {
                                    @Html.EditorFor(model => model.LRTireTypeId, EditorTemplateNames.RadioInputGroup, new
                               {
                                   RadioGroupName = "LRTireTypeId",
                                   RadioButtonValue = (i++),
                                   CurrentRadioButtonValue = Model.LRTireTypeId,
                                   Label = tireType
                               })
                                }
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-5 col-sm-6 col-md-6 ">
                                <h4>@Labels.RightFront</h4>
                                @Html.EditorFor(m => Model.RFRimScratch)
                                @{i = 0;}
                                @foreach (var tireType in Model.TireTypes)
                                {
                                    @Html.EditorFor(model => model.RFTireTypeId, EditorTemplateNames.RadioInputGroup, new
                               {
                                   RadioGroupName = "RFTireTypeId",
                                   RadioButtonValue = (i++),
                                   CurrentRadioButtonValue = Model.RFTireTypeId,
                                   Label = tireType
                               })
                                }
                            </div>

                            <div class="col-lg-5 col-sm-6 col-md-6 ">
                                <h4>@Labels.RightRear</h4>
                                @Html.EditorFor(m => Model.RRRimScratch)
                                @{i = 0;}
                                @foreach (var tireType in Model.TireTypes)
                                {
                                    @Html.EditorFor(model => model.RRTireTypeId, EditorTemplateNames.RadioInputGroup, new
                               {
                                   RadioGroupName = "RRTireTypeId",
                                   RadioButtonValue = (i++),
                                   CurrentRadioButtonValue = Model.RRTireTypeId,
                                   Label = tireType
                               })
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="damage-indication-holder">
                    @*@Html.SubmitButton(Labels.Reset, new { name = "action", value = "Reset", @class = "btn-save-inspection" })*@
                    <a class="btn-svg btn-twoLine">
                        <span class="icon-clear-all"></span>
                        @Labels.ClearAll
                    </a>
                </div>
            </div>
            <div class="col-sm-8 text-right">
                <div class="row">
                    <div class="col-lg-10 col-sm-12 col-md-12 ">
                        @{
                            var inspectionId = Model.Id.HasValue ? @Model.Id.Value : -1;
                            var appontmentPresentationId = @Model.AppointmentPresentationId.HasValue ? @Model.AppointmentPresentationId.Value : -1;
                        }
                        <a href="#" onclick="printVehicleInspection(@inspectionId,  @appontmentPresentationId, @Model.TenantId);" class="btn dropdown-primary btn-primary" id="print-button" data-toggle="dropdown">
                            <span>@Labels.Print</span>
                        </a>
                        @Html.SubmitButton(Labels.Services, new { @class = "btn btn-primary", name = "action", value = @InspectionNavigationActions.Services.ToString() })
                        @Html.SubmitButton(Labels.LOF, new { @class = "btn btn-primary", name = "action", value = @InspectionNavigationActions.LOF.ToString() })
                        @*<a href="#" onclick="printVehicleInspection(@inspectionId,  @appontmentPresentationId, @Model.TenantId);" class="btn dropdown-primary btn-primary" id="print-button" data-toggle="dropdown">
                            <span>@Labels.Print</span>
                        </a>
                        @Html.NavigationButton("Index", "MenuPresentation", routeValues: new { customerId = Model.CustomerInfo?.Id, carId = Model.CustomerInfo?.CarId, mileage = Model.CustomerInfo?.Mileage, appointmentPresentationId = Model.AppointmentPresentationId, inspectionId = Model.Id, transmission = Model.Transmission, driveLine = Model.Driveline, enteredMileage = Model.EnteredMileage, dealerVehicleId = Model.CustomerInfo != null ? Model.CustomerInfo.DealerVehicleId : null, vin = Model.CustomerInfo != null ? Model.CustomerInfo.VIN : null, CarIdUndetermined = Model.CarIdUndetermined }, text: Labels.Services, htmlAttributes: new { @class = "btn btn-primary" })
                        @Html.NavigationButton("Index", "LOF", routeValues: new { customerId = Model.CustomerInfo?.Id, carId = Model.CustomerInfo?.CarId, mileage = Model.CustomerInfo?.Mileage, appointmentPresentationId = Model.AppointmentPresentationId, inspectionId = Model.Id, transmission = Model.Transmission, driveLine = Model.Driveline, enteredMileage = Model.EnteredMileage, dealerVehicleId = Model.CustomerInfo != null ? Model.CustomerInfo.DealerVehicleId : null, vin = Model.CustomerInfo != null ? Model.CustomerInfo.VIN : null, CarIdUndetermined = Model.CarIdUndetermined }, text: Labels.LOF, htmlAttributes: new { @class = "btn btn-primary", id = "Lof" })*@
                    </div>
                </div>
            </div>
        </div>
    </section>
                                    }
<script>
    var damageIndications  = @(Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model.DamageIndications)));
    var inspectionId = "@Model.Id" ? parseInt("@Model.Id", 10) : 0;
    var commentModalTitle = "@Labels.DamageIndicationDetails";
    var addDIUrl = "@Url.Action("AddDamageIndication", "Inspection", new { area = "Dealer" })";
    var deleteDIUrl = "@Url.Action("DeleteDamageIndication", "Inspection", new { area = "Dealer" })";
    var editDIUrl = "@Url.Action("EditDamageIndication", "Inspection", new { area = "Dealer" })";
    var deletePhotoUrl = "@Url.Action("DeletePhoto", "Inspection", new { area = "Dealer" })";
</script>

@section scripts {
    @Scripts.Render(BundleNames.Inspection)
    <script>
        $(function() {
            smartvma.callbacks.updateCustomerMenuMileage();
        });
    </script>
}

SmartVMA/SmartVMA.Web/Areas/Dealer/Views/Inspection/_DamageIndicationTypes.cshtml
@model List<DamageIndicationTypeViewModel>
<h4>@Labels.DamageIndication</h4>

@foreach (var item in Model)
{

    <a href="#" title="@item.Name" data-iscomment="@item.IsComment" data-id="@item.Id" data-url="@item.Url" data-icon="symbol-@item.Name" class="symbol-@item.Name damage-indication-type">@Html.DisplayFor(m => item.Name)</a>
    @*<img src="@item.Url" alt="@item.Name" data-iscomment="@item.IsComment" data-id="@item.Id" data-url="@item.Url" class="damage-indication-type"/>
    @Html.DisplayFor(m => item.Name)*@

}

SmartVMA/SmartVMA.Web/Areas/Dealer/Views/Inspection/_VehiclePhotos.cshtml
@model List<VehiclePhotoViewModel>
@*<h4>@Labels.Photos</h4>*@
    @foreach (var item in Model)
    {
        <a href="@Url.Action("GetPhoto", "Inspection", new { id = item.Id, area = "Dealer" })" title="Details" class="photo-holder btn-modal">
            <img src="@item.Url" alt="Vehicle Photo" width="80" height="60" />
        </a>
    }
@*

template
<a href="#" class="photo-holder"><img src="~/Content/_images/VehiclePhoto1.jpg" /></a>
<a href="#" class="photo-holder"><img src="~/Content/_images/VehiclePhoto2.jpg" /></a>
<a href="#" class="photo-holder"><img src="~/Content/_images/VehiclePhoto1.jpg" /></a>
<a href="#" class="photo-holder"><img src="~/Content/_images/VehiclePhoto2.jpg" /></a>
<a href="#" class="photo-holder"><img src="~/Content/_images/VehiclePhoto1.jpg" /></a>
<a href="#" class="photo-holder"><img src="~/Content/_images/VehiclePhoto2.jpg" /></a>
<a href="#" class="photo-holder"><img src="~/Content/_images/VehiclePhoto1.jpg" /></a>
<a href="#" class="photo-holder"><img src="~/Content/_images/VehiclePhoto2.jpg" /></a>*@

SmartVMA/SmartVMA.Web/Areas/Dealer/Views/Inspection/_ViewPoints.cshtml
@model List<ViewPointViewModel>

<div id="carousel" class="carousel">
    @*@foreach (var item in Model)
    {
        <div>
            <div class="view-point-container">
                <img src="@item.Url" alt="@item.Name" class="view-point" data-id="@item.Id" style="position: relative; top: 0; left: 0;" />
            </div>
        </div>
    }*@

    <div>
        <div class="view-point-container carImg">
            <img src="/Content/_images/Front.PNG" alt="Front" class="view-point" data-id="1">
        </div>
    </div>
    <div>
        <div class="view-point-container carImg">
            <img src="/Content/_images/Left.PNG" alt="Left" class="view-point" data-id="2">
        </div>
    </div>
    <div>
        <div class="view-point-container carImg">
            <img src="/Content/_images/Back.PNG" alt="Back" class="view-point" data-id="3">
        </div>
    </div>
    <div>
        <div class="view-point-container carImg">
            <img src="/Content/_images/Right.PNG" alt="Right" class="view-point" data-id="4">
        </div>
    </div>
    <div>
        <div class="view-point-container carImg">
            <img src="/Content/_images/Top.PNG" alt="Top" class="view-point" data-id="5">
        </div>
    </div>
</div>